- .github/workflows/validate-entry.yml
This updated code adds a new GitHub Action workflow for validating entries. The workflow runs on every push and pull request to the main branch, using Python 3.9 on Ubuntu. It then installs necessary dependencies and runs a script to validate the entries.
> Add GitHub Action to validate entries

- listing.json
> ✨ Adding lmao

- listing.json
Reverts karnotxyz/avail-campaign-listing#167
> Revert "✨ Adding NomadValidator"

- .github/workflows/validate-entry.yml
- .github/workflows/validate.py
The GitHub workflow for validating entries has been updated to not only validate entries but also build and commit any changes. A new feature has been added to append validated entries to a JSON file. The workflow now commits this file and pushes changes to the repository, using the python validate.py script.
> Revise GitHub workflow to include build and commit steps

- .github/workflows/validate-entry.yml
- .github/workflows/validate.py
Reverts karnotxyz/avail-campaign-listing#202
> Revert "Revise GitHub workflow to include build and commit steps"

- app_chains/441dfb03-b5a7-40d7-af6e-6c3097258940.json
> Adding narutoruna

- app_chains/f1fbe762-6ced-493a-8169-df1159b1f6cd.json
f1fbe762-6ced-493a-8169-df1159b1f6cd.json
> create appchain f1fbe762-6ced-493a-8169-df1159b1f6cd.json

- app_chains/1514e249-641c-4f32-91e1-91b159a29a69.json
> ✨ Adding srrmemo

- app_chains/58488b21-fe74-4180-8a05-432acd0febce.json
> ✨ Adding wtlj

- app_chains/b66c1f35-cbae-4fb8-93d1-769afc203fbd.json
> ✨ Adding rAdius

- app_chains/c7ad6322-f487-48eb-82bb-824cec8f2b73.json
> ✨️Adding Himess

- app_chains/29969d4b-cb7b-47d1-b66e-8a6b25503f9e.json
> Adding erqjoenLicyxion217

- app_chains/58221b2b-34f6-4f59-bf81-014020b25228.json
- listing.json
> ✨ Adding Cosmostation

- app_chains/6c3dbc04-e6c6-4b77-8af8-0cc6b1869ca4.json
> add chenchiyuan chain

- app_chains/f3ddd2e0-ad7b-498e-bf05-811143308af3.json
> ✨Adding joeblack

- app_chains/2a8c6733-be77-479e-9834-42078df89cac.json
> ✨ Adding Kreb

- app_chains/edf467bc-d7e3-485b-8975-b8205e9ea8c3
> ✨ Adding erayg

- app_chains/eab0d886-436b-41d3-b04a-68c518d0ac52.json
> ✨ Adding Yellow

- app_chains/581e2e8f-9643-43d0-b244-ac9452a3f04c.json.json
> ✨ Adding PARSA

- app_chains/d9abc1eb-5fda-4dc9-97a5-d7ab1dda430f.json
> ✨ Adding Togata

- app_chains/92846889-dbcf-4ee4-a89d-0c4cd67674cc.json
Adding a new app chain by adding all the relevant details in a JSON file inside the `app-chains` folder
> ✨ Adding vahidnfcm

- app_chains/3bcef176-b57c-4cc6-a9c9-d8d216f95529.json
> ✨ Adding 'digitclone'

- app_chains/d31c73d5-417b-44b4-8340-26fb667cf02b.json
> ✨ Adding Rewikimember

- app_chains/7e9a0b3e-76e8-4512-8031-0f305a7ae848 (1).json
[7e9a0b3e-76e8-4512-8031-0f305a7ae848 (1).json](https://github.com/karnotxyz/avail-campaign-listing/files/14152227/7e9a0b3e-76e8-4512-8031-0f305a7ae848.1.json)
> Adding encoderrr

- app_chains/7e9a0b3e-76e8-4512-8031-0f305a7ae848 (1).json
Reverts karnotxyz/avail-campaign-listing#1731
> Revert "Adding encoderrr"

- app_chains/0ad8c732-f192-4a1f-a7ea-07f519fa452f.json
> ✨ Adding crypgo

- app_chains/30105cc4-75e2-4361-a19d-a3022b22a0b8.json
> 30105cc4-75e2-4361-a19d-a3022b22a0b8.json

- app_chains/705cc859-a1ef-496a-8bfa-850880e8ecb3.json
> ✨️Adding frinchity

- app_chains/2234840f-08dd-4e89-9ee2-573c58cb0af1.json
> ✨ Adding aydune

- app_chains/e82db9bf-50bc-4ea7-a61d-a06113cbeb0c.json
> ✨ Adding mhmt

- app_chains/e94d11b7-0fc8-41bf-9605-8c6e1818c443.json
> ✨ Adding FTX

- app_chains/be1ed75a-61e0-4f40-94a9-884b8be7846a.json
> ✨ Adding Mentalist

- app_chains/52d7755a-9079-4bc6-bf7e-09b16c9e7ccd.json
> ✨ Adding benar

- app_chains/878fd4d7-fbf8-4452-9b58-fa769b6bb86a.json
madara pull request for avail project
> ✨ Adding madarakutlu01 on avail

- app_chains/71de63d1-c676-4ae1-b0dc-b51964769a91.json
> ✨ Adding poolad

- app_chains/7796892f-d511-419c-bfe9-2b102a9f2f44.json
> ✨ Adding reedchain

- app_chains/36bb0479-23d3-4de8-b239-d1ce9bff846c.json
[36bb0479-23d3-4de8-b239-d1ce9bff846c.json](https://github.com/karnotxyz/avail-campaign-listing/files/14154585/36bb0479-23d3-4de8-b239-d1ce9bff846c.json)
> 36bb0479-23d3-4de8-b239-d1ce9bff846c.json

- app_chains/b44896ee-a728-4f3f-a0ae-27c541a5a232.json
> ✨ Adding haciyatmaz

- app_chains/9bc9f8da-9f34-45e4-95f6-1c21799d0d4c.json
> ✨ Adding almoalmo

- app_chains/f72a2683-6221-4f17-bc11-4ab2c68bf591.json
> ✨ Adding LYL42

- app_chains/09f042d8-88d1-4973-996d-b74987352e31.json
> ✨️Adding kongar

- app_chains/f08409f0-5815-41e3-9a86-302d136feed5.json
Discover the power of Avail with Herasoft App!
> ✨ Adding Herasoft App

- app_chains/5413a932-e620-45af-80e8-db56dfbb8bf9.json
> ✨ Adding tr3mm

- app_chains/d5993089-0db3-4cac-aa4f-559aeabf420f.json
> Adding fewqvuLiWcyxfghr99213

- app_chains/27d36ea1-5f6e-442d-937c-bb66d4facb65.json
> ✨ Add zeep

- app_chains/e1681168-83aa-4c0e-b602-c97f529e2874.json
[e1681168-83aa-4c0e-b602-c97f529e2874.json](https://github.com/karnotxyz/avail-campaign-listing/files/14155287/e1681168-83aa-4c0e-b602-c97f529e2874.json)
> add fible1

- app_chains/058f248d-374d-48a4-bcbd-2797cb4c5856.json
[058f248d-374d-48a4-bcbd-2797cb4c5856.json](https://github.com/karnotxyz/avail-campaign-listing/files/14155575/058f248d-374d-48a4-bcbd-2797cb4c5856.json)
> Adding Dicounter

- app_chains/1de037c4-152b-4cc4-b0ff-d4710469eb35.json
> ✨ Adding 0xeyc

- app_chains/ac00ab2f-36be-41c9-b851-d2756c652e55.json
[ac00ab2f-36be-41c9-b851-d2756c652e55.json](https://github.com/karnotxyz/avail-campaign-listing/files/14146254/ac00ab2f-36be-41c9-b851-d2756c652e55.json)
> Adding fatjarmi_mdr

- app_chains/ea87c438-a3d9-4467-af69-07b3cafcceba.json
[ea87c438-a3d9-4467-af69-07b3cafcceba.json](https://github.com/karnotxyz/avail-campaign-listing/files/14154384/ea87c438-a3d9-4467-af69-07b3cafcceba.json)
> ✨ Adding Monkeygold

- app_chains/60493f48-5cd2-4923-89e8-c2fa85dadc1c.json
> Adding nefsim

- app_chains/d23269d2-c9e8-46f9-9983-f3d850b6f6d3.json
> ✨ Add FroggyChain

- app_chains/2bd1cf8a-cb61-4b16-87bb-40e9fdbc070c.json
{
"name": "krptocvn",
"logo": "https://r.resimlink.com/pU-YE5.png",
"rpc_url": "http://178.62.211.85:9944",
"explorer_url": "http://178.62.211.85:4000",
"metrics_endpoint": "http://178.62.211.85:9615/metrics",
"id": "2bd1cf8a-cb61-4b16-87bb-40e9fdbc070c"
}
> ✨ Adding krptocvn

- app_chains/912e4381-09b5-453e-9aac-162b387c3808.json
> ✨ Adding HakanN

- app_chains/42d1dd0e-21d7-40e5-b770-ffee5cfffcdf.json
> Adding Yanli777899cyx

- app_chains/3a85d459-e7ad-486d-bd50-367ebc224cae.json
> ✨ Adding ati-avail1

- app_chains/364cc5d3-b9b8-48b1-ab4c-59f741d425df.json
Add CoinStudio. New PR, last one closed after pending dor 3 days. Please review.
> Add CoinStudio 364cc5d3-b9b8-48b1-ab4c-59f741d425df.json

- app_chains/2ba48671-53d9-426d-949e-008f2245f519.json
Create 2ba48671-53d9-426d-949e-008f2245f519.json
> ✨️ Add New Sharkstar

- app_chains/6c266d10-5cf7-43b5-99ab-54b53539ea2e.json
This is my first Avail AppChain named nikita
I want to work on this system and customize it by using oracles to collect the required data and isolate them as customized for the user.
> ✨ Adding AppChain nikita ✨

- app_chains/906834ca-6f7b-44ad-acf9-1eeeb9f290bc.json
> ✨️Adding fablo

- app_chains/c59f62d9-12c7-446e-bb14-e9742b54ba12.json
> Adding silvercatApp

- app_chains/cbd06d28-5ea5-4d89-9b2c-ef36f77e13cc.json
> ✨ Adding rustv

- app_chains/6a010ed2-3eb1-4d5b-92c9-072233b7bf34.json
This is my first Avail AppChain, bloodisland
> Adding AppChain bloodisland

- app_chains/69555f18-7736-4e31-a860-de1057840649.json
> ✨ Adding blackmirror

- app_chains/81bc1f05-6057-4594-82a5-229758e2b704.json
> ✨ Adding CryptoMaster

- app_chains/7262afde-3460-4e45-aefd-948469af120f.json
> ✨️Adding alba

- app_chains/75ee2b0d-d06b-48d5-ab99-12375d695742.json
Avail Madara App Chains Karnot
> ✨ Adding blackstar

- app_chains/688f89b9-4095-42c2-88c8-c1fa81b7e51c.json
> ✨ Adding NijatChain

- app_chains/e49b67e1-7072-4885-884e-7ef4116a3639.json
> ✨ Adding zaza

- app_chains/05349b9d-6edf-4831-bd0d-79cf1ca48132.json
> ✨️Adding rockwell

- app_chains/977c63de-c071-456c-9c31-ad25779d3fdd.json
[977c63de-c071-456c-9c31-ad25779d3fdd.json](https://github.com/karnotxyz/avail-campaign-listing/files/14156785/977c63de-c071-456c-9c31-ad25779d3fdd.json)
> Adding hodor

- app_chains/ff08d88a-72b6-4305-b21b-49e6712f43e9.json
> Adding vikanren

- app_chains/e62b6a86-5c46-4fa8-a7ab-49e9889f5e6f.json
> ✨️Adding PYDOI

- app_chains/a95e5908-bbfb-478c-84d0-188f1e836689.json
> Adding cyxxxxx

- app_chains/7fe43a4a-8ca4-4965-a26d-286345c81286.json
> ✨ Adding mert-avail2

- app_chains/a9c5462a-753f-4e59-bf15-0b739cdbdd98.json
> ✨ Adding ArramassChain

- app_chains/59961d8f-c8cb-4ccd-8f62-7810aae55232.json
> Adding lihxgcyxeenb

- app_chains/a8685c21-77c9-475c-96e1-11eaa193cb6e.json
This is my first Avail AppChain named leek
> ✨ Adding AppChain leek

- app_chains/3588588f-ba01-480a-9750-53a8180b974d.json
> Adding Burqrcyxlys

- app_chains/b0e5a2c4-bc50-4f5e-92d9-9e1554bebe0a.json
> add coinowo

- app_chains/92a80b61-7007-4191-a55c-a66a7b011c93.json
> ✨ Adding 0xNodes

- app_chains/b1c0bf1d-b295-4df1-8dcc-59003cf7921a.json
> ✨ Adding 'nonoao'

- app_chains/c85739d5-4df8-4bc3-a3f4-b8a6a511c909.json
> ✨ Adding robbert

- app_chains/e4b6f09d-f415-4e4f-9d93-a5781352268c.json
> Adding tbcyxmneoea

- app_chains/ed64701d-a16b-4dd9-87d4-400cd8ef6ebb.json
> ✨️Adding ynranil

- app_chains/0e792fbf-337b-4728-bb1b-a4f511e62f45.json
Combining Oracle and Social Graph in an isolated environment
> Adding nikitaa

- app_chains/f0721fa5-a3fe-4043-a367-401fbd38798e.json
> Adding sydgvmjvfacyxtn

- app_chains/d2e92728-05a2-47e6-9d37-90ca0a15ee50.json
Because of the new file structure, I closed the old pr and updated the new one according to the new structure.
This is the old one
https://github.com/karnotxyz/avail-campaign-listing/pull/58
> Adding inspector44 again using new structure

- app_chains/09d6711e-b9b4-4837-949c-6a1fade9b9f9.json
> Adding mmaguyfnpjzwcyxvmi

- app_chains/6233517a-ce0b-47e0-8c8d-00018857693a.json
> ✨ Adding ARSAvail

- app_chains/cb5d05af-633f-41f4-8a6a-c63dbe3cefc7.json
> Adding 'fiatsend' 

- app_chains/9fe953df-9b26-4fe3-b3e0-73dcef14cd31.json
> Adding bdjnflhbdqcyxxyq

- app_chains/88c3e5ee-c52a-403b-be8e-f2e38934ce88.json
> Adding dfvcyxre

- app_chains/ddd1cf16-1678-45d9-af74-84050ef6b829.json
> ✨ Adding MaxWell

- .github/workflows/validate.py
Reverts karnotxyz/avail-campaign-listing#2504
> Revert "fixes: Added Check for validating File name & App Chain Id in File"

- app_chains/d7a9c549-e77e-42ae-9f6e-6a942177bcdf.json
Avail yarofeyka-madara App chain
> ✨ Adding yarofeyka-madara

- app_chains/ad38d2d4-65e4-46b2-8682-fe159d5391a1.json
> ✨ Adding boss

- app_chains/38cb4974-3835-49f3-8eb6-79b8a2e942f8.json
> ✨ Adding YAGUN

- app_chains/0c6b9cbb-5965-4b25-abd9-deb873bed8c3.json
Create 0c6b9cbb-5965-4b25-abd9-deb873bed8c3.json
> ✨️Adding Ahmkah 

- app_chains/90bd2386-223d-42a1-a1c5-356d6e7a002d.json
> Added Okrek AppChain

- app_chains/28b6ead5-e87d-460c-bf51-c918af12dba3.json
This is my first Avail AppChain named "Wall.e" -a groundbreaking appchain aiming to regulate energy consumption efficiently. Leveraging smart contracts and decentralized governance, "Wall.e" seeks to strike a balance in supply and demand, fostering sustainability and community engagement.
> Adding "Wall.e"

- app_chains/a5f7a3d0-00e2-47f5-ba90-97ef9b09c5c6.json
> ✨ Adding DOCGUIRA

- app_chains/9c938d91-6bad-469b-a741-a9c074abb2a8.json
This is my first Avail AppChain named apex
> ✨adding apex

- app_chains/117f409d-452f-4078-8df8-779afeb91277.json
> AppChain TransfertASTR

- app_chains/1c838d0c-06f2-4d2c-af77-a939f3e438f6.json
This is my first Avail AppChain named vortex
> ✨adding vortex

- app_chains/9596ca4e-98bb-434f-a18b-2b2d6723d1cf.json
> ✨ Adding Coha05

- app_chains/4c2b7fbd-7f07-49b0-90ab-3a0c47eeadc9.json
> Adding cyxdfg

- app_chains/b8248b29-d2e0-4ef1-b222-805620e23714.json
> Adding fdacyxgds

- app_chains/66642fcf-2afd-432d-8d40-f399f7a60e93.json
> Adding cyxccxc

- app_chains/f24a43d9-f999-45d7-af2e-a63a9a443954.json
> Adding adfgcycyxfds

- app_chains/c14f4b73-a885-4250-8bee-7bba3216844c.json
Equinox: A Appchain powered by Avail.
> ✨ Addingadding equinox

- app_chains/66890415-3a93-4a89-860f-c453b3077ecf.json
> ✨ Adding AppChain MoMoApp

- app_chains/1519db45-b81d-41c2-9b08-c58e3648ca23.json
Chronos is a Appchain by leveraging Avail, more features will come soon!
> ✨ Adding chronos

- app_chains/a04d1624-ebc3-4867-abe9-8c3a79c2586a.json
> Adding d932fewqctxcyx

- app_chains/30a747fd-3c2c-4177-af3f-b5805ec32302.json
> Adding cqwet78cyxios

- app_chains/c901d970-1694-4343-9416-981f9dc1b848.json
> Adding kkocyxbpxnlpjzxfkvl

- app_chains/a138167c-9a00-442d-8110-0cb5c78fc27f.json
This is my first app named shimauma
> Adding shimauma

- app_chains/8176e085-4720-4fe0-8cc9-40d80c162332.json
> Adding zfnwcadrwfnbcyx

- app_chains/c7c839e2-95d7-48e1-8f8e-ad5ef4288f4a.json
> Adding '0xnana'

- app_chains/551d67a2-ba9d-409e-b0a3-37c2998b8446.json
[551d67a2-ba9d-409e-b0a3-37c2998b8446.json](https://github.com/karnotxyz/avail-campaign-listing/files/14163368/551d67a2-ba9d-409e-b0a3-37c2998b8446.json)
> HungryWolf1372

- app_chains/246c6af2-6aa4-43a6-b7d2-59576a167c68.json
> ✨ Adding 'Suskesorg'

- app_chains/13b63a75-c536-48e8-a4c0-94b4e7705e5f.json
> Adding 'mrcatvmx'

- app_chains/8cd981cb-ea74-4d5c-9968-5b6c68a76202.json
> adding vanpham

- app_chains/b6f8c529-d078-42a3-8008-37d4e192973d.json
> ✨ Adding candy

- app_chains/e92b8c7e-ee1c-4f0a-a71b-ab48b4e16937.json
> ✨ Adding atacoin

- app_chains/8a0f5ea9-cc5f-4846-bbc3-a683733b7e31.json
> ✨ Adding hamed1990

- app_chains/440808dd-b0c1-4937-ac8f-cf7dfa3d2fff.json
> Adding "avail-1"

- app_chains/1a4cab29-4aa8-4e4b-a153-f6271ab3d861.json
[1a4cab29-4aa8-4e4b-a153-f6271ab3d861.json](https://github.com/karnotxyz/avail-campaign-listing/files/14165562/1a4cab29-4aa8-4e4b-a153-f6271ab3d861.json)
> Adding Cryptoply_2023

- app_chains/e141cab4-a4cf-4c2d-a3c7-b0ac9213e5fb.json
This is my first AppChain on Avail Testnet
> APPbuss Chain

- app_chains/504bd3f2-9bcb-4a41-bfa9-76f7de7c8972.json
This is my first Avail AppChain named Kalao
> ✨ Adding AppChain Kalao

- app_chains/9584fac9-3fb0-4166-8266-988cd04eb542.json
{
"name": "0xmofcous",
"logo": "https://i.ibb.co/1snKbfP/logo.png",
"rpc_url": "http://91.108.241.88:9944",
"explorer_url": "http://91.108.241.88:4000",
"metrics_endpoint": "http://91.108.241.88:9615/metrics",
"id": "9584fac9-3fb0-4166-8266-988cd04eb542"
}
> ✨ Adding 0xmofcious

- app_chains/3f8708c5-7906-4f96-b94a-f4b6cc6ed80e.json
Submitting my AppChain as KLOB
> 3f8708c5-7906-4f96-b94a-f4b6cc6ed80e.json

- app_chains/c901d2fa-7ef5-4a58-bb0e-fd45e1522899.json
> adding icarus

- app_chains/e4b7fbab-25cd-4f97-b6e8-bfb1232b3af7.json
> Adding mrcatvmx

- app_chains/b022033b-7bf1-46bc-91b0-8aebde10c9c9.json
[b022033b-7bf1-46bc-91b0-8aebde10c9c9.json](https://github.com/karnotxyz/avail-campaign-listing/files/14167929/b022033b-7bf1-46bc-91b0-8aebde10c9c9.json)
> Adding kalantar20

- app_chains/675006b6-72e1-4539-b112-3e1ef165e89a.json
> ✨Adding moraa

- app_chains/108e7ca0-65a7-4cb2-ada5-6a0dd04fcca8.json
> Add cryptohouse

- app_chains/385d63b2-9be0-4784-97a5-d64e531e67f1.json
> ✨ Adding chelsea

- app_chains/2c0e1ee7-bcec-4cd5-8e96-2ac29f67b54c.json
This is my first Avail AppChain named thuongdh
> ✨ Adding AppChain thuongdh

- app_chains/65b084db-cdea-487b-bf3f-6da13b9a4948.json
> ✨ Adding islam7070_avail

- app_chains/c02a2500-34cc-431b-af6a-4f42cf0c54c4.json
[c02a2500-34cc-431b-af6a-4f42cf0c54c4.json](https://github.com/karnotxyz/avail-campaign-listing/files/14170726/c02a2500-34cc-431b-af6a-4f42cf0c54c4.json)
> adding dexter

- app_chains/e15c0598-8767-4285-a914-bfe9f535851c.json
> Adding Renrub821

- app_chains/ae949546-326c-418f-a5b0-25f727711fe7.json
> ✨ Adding faruk

- app_chains/3df2109b-8844-40aa-8aab-8f9b2b66ce45.json
Second try with good .json name file
> Adding mini_labs

- app_chains/060472da-e7ef-48d1-9115-6cb283385466.json
> ✨ Adding Godofsol

- app_chains/ceed35bf-a51b-41f9-8c7a-966eaa2f3fd5.json
> ✨ Adding jaberi

- app_chains/207bc0b5-ac21-4b3b-8059-b279936fdf92.json
> ✨ Adding vaji83

- app_chains/4fab0d27-e2f5-4892-9a5e-2a9a6ef602e9.json
> ✨Adding AZARAZIII

- app_chains/e6273b2c-d506-4cac-a5ca-f2d740d980c5.json
- e6273b2c-d506-4cac-a5ca-f2d740d980c5.json
> ✨ Adding 'Solo'

- app_chains/2847b241-0c6c-44fe-94b2-b250521fba4f.json
> ✨ Adding esmail

- app_chains/d74d0b0f-2f2b-4b86-b57c-a56cd281387c.json
> ✨ Adding krtl

- app_chains/ee7a340f-2b02-4683-8664-9a1ff36f3777.json
> ✨ Adding nasser215

- app_chains/f8e365f9-2611-4491-bd49-a1cc56237360.json
Mach5 Validators Avail AppChain
> ✨ Adding AppChain Mach5-Validator files via upload

- app_chains/78b7f506-9536-499c-a161-3e48b9a432a7.json
> ✨ Adding duck

- app_chains/f50047da-9860-4500-8340-32854df09414.json
> ✨️Adding hobit

- app_chains/012504b5-7d1a-42de-bfe1-e89d59a82546.json
> ✨️Adding sayi

- app_chains/93c7dc20-71dc-4a88-a457-70327bede7b3.json
> ✨️Adding padra

- app_chains/010b4ae9-4ad9-4921-9651-b6adb24358a3.json
> Adding AppChain DPG NR

- app_chains/18cd5d6f-093f-4053-9423-f26e94962130.json
> ✨️Adding crixus

- app_chains/7982ed19-363b-4918-89d0-f984a75b9904.json
- app_chains/cb00713a-b09f-480c-8b49-5132276f0a4c.json
> ✨️Adding canoplos

- app_chains/70d065e3-c046-4383-b4d9-3f20fe961232.json
> ✨ Adding NFTBARN

- app_chains/94da56c9-5ac6-44f1-9dc2-435f4214fa59.json
This is my first Avail AppChain named Farez
> ✨ Adding Farez

- app_chains/3b5378d7-64f5-4f63-a01e-b10c284559ca.json
> ✨Adding manwemadara

- app_chains/e72440a4-c077-4e0f-a8dc-ab10980acf96.json
> ✨ Adding Pikachu

- app_chains/46cd78e5-889c-404d-9484-baa98df31623.json
> ✨ Adding Sara

- app_chains/e12b25f6-211a-4092-9ad4-525363fee62b.json
> ✨ Adding stevens

- app_chains/eb4b3f51-a1b2-4c86-a0f9-ed93dc48f5e7.json
> Adding willloh1314

- app_chains/23dfd33d-fb8f-420d-a13a-d6270ac66393.json
> ✨ Adding cebiko

- app_chains/cc33df86-981a-45e5-b4ed-79b378c69634.json
[cc33df86-981a-45e5-b4ed-79b378c69634.json](https://github.com/karnotxyz/avail-campaign-listing/files/14183695/cc33df86-981a-45e5-b4ed-79b378c69634.json)
> Adding Xepi

- app_chains/f43c3e32-47dc-49a9-a868-34ae6c4c1240.json
> Adding darkforest

- app_chains/5810108d-e070-4d50-81a1-23df653ffd16.json
This is my first Avail AppChain named TRUMP
> ✨ Adding TRUMP

- app_chains/cbee4153-e3b3-417d-ae4d-da1140b7f358.json
> ✨ Adding laksApp

- app_chains/973c1eee-c4d1-4374-bf10-2df687d852a2.json
> ✨ Adding oldboysr

- app_chains/b95bf4d5-d80d-42d4-88cd-dac1e8f32dd2.json
> ✨Adding salar7

- app_chains/32169090-cec9-4930-a469-4aee9b76bb66.json
> Adding nirvana 

- app_chains/522a5cb5-1ac8-40fa-a5be-095004aa52b4.json
This is my first Avail AppChain named "hand"
> ✨ Adding AppChain hand

- app_chains/c7ed2556-d62b-40cf-9ebd-dabf35c66415.json
Add config json file for Avail app-chain jikioph
> Add config json file for Avail app-chain name jikioph

- app_chains/def087e9-d5cb-406a-8076-b1bd7aa1e295.json
> ✨ Adding rrrpmian

- app_chains/8aa67740-6098-4742-802c-8fa4c84c3f36.json
> ✨ Adding avestal

- app_chains/a2895a8e-28f2-45a8-9799-eb259db26290.json
> ✨ Adding Wild

- app_chains/7b6a0091-1de9-496b-8fee-3d0cdd22428e.json
> adding zulu

- app_chains/b2f18adc-64e8-4fea-a40a-7133bd1841c4.json
> ✨ Adding QTxCT

- app_chains/ed944104-57c6-4e22-8648-b0f4af829105.json
> ✨ Adding hysis

- app_chains/2b22380e-e6ed-4bad-aa9d-a8dbeee931f0.json
> ✨ Adding Aysun

- app_chains/e8e12724-5e3f-4f97-b472-3ea87c78a4ef.json
>  ✨ Adding kamrancoin

- app_chains/8755c9bf-944a-4a4e-9ddf-3363596b776f.json
> ✨ Adding Osmium

- app_chains/b925410e-cc78-43e1-9ce7-2fcefb5ec2eb.json
> ✨ Adding omid

- app_chains/13676e24-59f0-43c9-aa26-1e0ed4e37c08.json
> Adding 'basam'

- app_chains/c6300332-1031-437b-b127-d022f27dd87a.json
This is my first Avail AppChain named sairensu
> ✨ Adding AppChain sairensu

- app_chains/700d67c6-a614-4a78-bdc3-b6ba46151268.json
add 700d67c6-a614-4a78-bdc3-b6ba46151268.json
> add kavail chain

- app_chains/75f28122-e0af-4f99-bbb3-3ecc19c2f250.json
> ✨ Adding SamedovWorkingSpace

- app_chains/b2d57804-bf3e-4cf3-a5e7-3b17d161e4af.json
> ✨ Adding Hosein

- app_chains/24ca37c3-f010-4213-ab17-32530388c965.json
> Add william1314

- app_chains/6aa6229c-5ac5-4d82-abfd-42f7614d5a1f.json
> ✨ Adding altare 

- app_chains/ef202f3d-382a-4d73-8a9b-5334273b4f04.json
> ✨ Adding hamid

- app_chains/4d5720a4-2282-4310-8a08-64d27639468d.json
This is my first Avail AppChain named jijicats
> adding jijicats

- app_chains/8f3ecaa6-d1a5-4c6b-a4f0-729a67d362f6.json
> ✨ Adding gs4ever

- app_chains/47d04694-955a-487b-8186-c9c1bb67aa5b.json
This program is to isolate the user's social graph
> Adding emma

- app_chains/abc18513-1a71-499f-ab2a-2339afbdb3c5.json
This pull request adds a new chain named "lightcone" to the project.
Chain Name: lightcone
Explorer URL: http://5.42.84.59:4000
Description:
This pull request introduces a new chain named "lightcone" to the project. The "lightcone" chain will serve as a [provide a brief overview of the purpose or function of the lightcone chain]. The chain's explorer is accessible at [provide a clickable link to the explorer URL].
Please review and merge this pull request at your earliest convenience. Thank you!
> Adding lightcone

- app_chains/b1b3a74c-d1f9-4f55-b881-c53a117e661a.json
This is my first Avail AppChain named alfan
> Adding alfan ✨

- app_chains/69e389ff-4fd9-488c-8930-caea8348a2bf.json
> ✨adding hamid

- app_chains/58c9f887-3c71-4cbb-a3c7-f62cb42836f7.json
> ✨ Adding Madhakan

- app_chains/9fcaaae7-54b4-49e1-9ef7-be6acdefe2ba.json
Adding [VivekOnChain] App Chain
> ✨ Adding VivekOnChain

- app_chains/7e6a19d4-c326-49ba-bf4a-52cfdffd3f63.json
This program is to isolate the user's social graph
> Adding s8erlock

- app_chains/58317b74-9776-458f-8533-a5a3c7a985b1.json
Avail Testnet Kocasinan Vp App Chain
> Avail Kacasinan

- app_chains/3b949840-60cc-4707-b5f2-783043ba1286.json
[3b949840-60cc-4707-b5f2-783043ba1286.json](https://github.com/karnotxyz/avail-campaign-listing/files/14195516/3b949840-60cc-4707-b5f2-783043ba1286.json)
> Vivaldi1993

- app_chains/f26d0520-6244-440c-a81f-9cdee98ee622.json
Adding Rezo App Chain
The first , is currently in the ideation phase with plans for development in the near future. These days, Testnet provides conditions for conducting tests, and trial and error will be carried out for future development.
> ✨ Adding Rezo

- app_chains/8b5c6ffb-bbfc-4095-aec3-d92866cf30b8.json
Adding a new app chain by adding all the relevant details in a JSON file inside the app-chains folder
> Adding 'kangenboci'

- app_chains/3073dc7e-e41d-40b9-83fc-db5d6e9f7133.json
> ✨ Adding bajo

- app_chains/ff0f7a5c-4736-46f0-bea1-6f2d91ae5e35.json
> ✨ Adding osmanates

- app_chains/6da2a4f3-088f-4ded-a9fc-d2393fc84781.json
> Adding peyote

- app_chains/b1077185-4b70-4523-a947-a35c4871b328.json
Avail madara alcibiades app chain
> ✨ Adding alcibiades

- app_chains/1296fa52-6f86-461f-a23c-5ee5d3ab1bae.json
> ✨ Adding tizdandoon

- app_chains/88b753c9-3d2f-44e4-9130-78762dedf13a.json
> ✨ Adding toubaho

- app_chains/74aed522-90f8-4252-a492-4ce8d0f51205.json
[74aed522-90f8-4252-a492-4ce8d0f51205.json](https://github.com/karnotxyz/avail-campaign-listing/files/14200054/74aed522-90f8-4252-a492-4ce8d0f51205.json)
> Adding Ponyo

- app_chains/6858cbbc-a6fc-4f9f-ae49-c88d8175b1a4.json
> ✨ Adding BlueStar

- app_chains/f9898c3f-0432-4cda-bd47-d5690b4aa3ff.json
> ✨ Adding f9898c3f-0432-4cda-bd47-d5690b4aa3ff.json

- app_chains/67b28372-cd73-4e3c-a7e7-96bce40945e9.json
> ✨ Adding SanFrancisco

- app_chains/1703c378-bdc3-4443-8da6-bf2732036908.json
> ✨ Adding Bignode

- app_chains/3b5ae10e-9539-45a0-bdef-fa2497a11a3d.json
> ✨ Adding Kehsaneth

- app_chains/2291d675-9fe1-426f-9251-01464af0002d.json
Adding Captainsilver App Chain
> ✨ Adding Captainsilver

- app_chains/2306f3af-7d1b-41c1-bcaa-920dfdb237bf.json
> ✨ Adding Korgan

- app_chains/74566619-fa7c-48ee-a1be-ae440c455dd3.json
> ✨ Adding callmeozzy

- app_chains/c71a3298-c5c0-4c1d-ba99-7a6d83995edb.json
[c71a3298-c5c0-4c1d-ba99-7a6d83995edb.json](https://github.com/karnotxyz/avail-campaign-listing/files/14201386/c71a3298-c5c0-4c1d-ba99-7a6d83995edb.json)
> Adding barsava

- app_chains/0a167d97-b86a-4627-936d-dd4963a535b2.json
> ✅ Adding New AppChain : YOUSRA90

- app_chains/e4fb3295-f868-4e68-b10e-4d4741588232.json
> ✨ Adding su app chain

- app_chains/888c07d2-5f7f-431c-bb73-b432198982e8.json
> ✨ Adding milord123

- app_chains/786bb6f6-ec90-451e-9a3e-07d16008458d.json
{
"name": "ayoub",
"logo": "https://r.resimlink.com/MBrx4AdI1_.png",
"rpc_url": "http://185.249.227.7:9944",
"explorer_url": "http://185.249.227.7:4000",
"metrics_endpoint": "http://185.249.227.7:9615/metrics",
"id": "786bb6f6-ec90-451e-9a3e-07d16008458d"
}
> ✨ Adding ayoub

- app_chains/7527de70-8917-4fca-8713-e2daeb945e80.json
> Adding Fantasytale

- app_chains/cca64ff7-a29e-42f5-ac92-7b824ef402e7.json
> ✨ Adding ps50

- app_chains/38dd87eb-909e-4d8d-ae4d-a0f827e5c695.json
> ✨ Adding coliva

- app_chains/aa886ef2-9497-42b7-bffd-0d0ab0456754.json
> ✨Adding somayememar

- app_chains/baaa5a48-b1b9-467f-8229-fa5651ea529e.json
> ✨ Adding 100guc

- app_chains/801aaf75-b3ae-46ca-bedb-5ccd3b4b91cd.json
This is my first Avail AppChain named sukmachain
> sukmachain

- app_chains/d2e8d73b-9a14-445a-8853-18486b1f4f24.json
> ✨ Adding bbros

- app_chains/7402601c-701d-4a74-b04d-aec4681088ae.json
> ✨ Adding sentariona

- app_chains/1582cc65-b69a-4281-84d6-af1ed08390bf.json
> ✨ Adding amir89

- app_chains/49e06634-26f1-45b9-8288-6b280fc132e1.json
> ✨️Adding ekaronode

- app_chains/bbb66a6c-1e9c-48b7-98e9-e3641c8b3796.json
> Adding belalm

- app_chains/d9c484ce-5d0b-40f2-a000-cd9d7182218b.json
> ✨ Adding Bavorak

- app_chains/afffeb96-e33d-43d5-aa9f-50d36028a625.json
> Adding niko112

- app_chains/69a8d44e-f708-4c93-9f00-4026f17416da.json
> Adding niko111

- app_chains/13249bcc-88f3-4017-b743-d58ab5080adb.json
> ✨ Adding AppChain CJNode

- app_chains/fb6c2a58-9916-402c-bcda-c81e83e43251.json
> ✨ Adding new chains

- app_chains/89cb5ba6-5a2f-4521-8884-02ce98b81a89.json
> ✨ Adding AppChain zhenli

- app_chains/cd0265b8-a026-4b41-b19c-dd9becfc100c.json
> Adding niko110

- app_chains/f734d7f4-65c0-4b9c-95af-67aaf02f1c86.json
[f734d7f4-65c0-4b9c-95af-67aaf02f1c86.json](https://github.com/karnotxyz/avail-campaign-listing/files/14211006/f734d7f4-65c0-4b9c-95af-67aaf02f1c86.json)
> Adding Parsa

- app_chains/c893780e-5fc1-46ef-bd91-20acb2bbb427.json
> Adding Alphaniko

- app_chains/bff827b1-f2cc-497b-926c-a79bdaf16bcc.json
> ✨ Adding Aliirz1992

- app_chains/da58f17e-d4ed-42d7-aeb1-a2efdc9b7bd4.json
>  ✨Adding nojan

- app_chains/4498f5c1-5f12-452e-ae50-3b5ec578118c.json
Adding hosseindaraei App Chain
> Adding hosseindaraei

- app_chains/2e901b78-6e16-4eb2-9287-81da6098878e.json
> ✨ Adding AppChain michy

- app_chains/8cab20c1-c58a-458f-bc96-7cc464d2f000.json
> ✨ Addding hrzaree

- app_chains/69b98edc-0f67-454d-88e2-6e7f6243d98f.json
> ✨ Adding sepoool

- app_chains/194c3b00-39f8-4754-9467-038f8435533a
- app_chains/194c3b00-39f8-4754-9467-038f8435533a.json
[194c3b00-39f8-4754-9467-038f8435533a.json](https://github.com/karnotxyz/avail-campaign-listing/files/14208980/194c3b00-39f8-4754-9467-038f8435533a.json)
> ✨ adding Mrnoorian

- app_chains/013ddf9a-ffc2-46f4-bdfa-6add31022845.json
[013ddf9a-ffc2-46f4-bdfa-6add31022845.json](https://github.com/karnotxyz/avail-campaign-listing/files/14211738/013ddf9a-ffc2-46f4-bdfa-6add31022845.json)
> ✨ Adding SinA

- app_chains/64e095ca-4b35-4107-9c84-b2f7c24baae3.json
This is my first Avail AppChain named kinoko
> ✨ Adding AppChain kinoko✨

- app_chains/5bbaf04b-cef6-4a4c-8ede-75069600fca3.json
> ✨ adding arvin

- app_chains/5150571b-9efa-4ff8-896a-895ed20d2641.json
> ✨ Adding AppChain matt

- app_chains/bfff9e6c-ba8a-4b25-bab1-e1574336176f.json
> Adding neloking

- app_chains/c5d9a3b5-dca8-4b4b-94d3-a9b681879d56.json
> ✨ Adding AppChain johnwick

- app_chains/e92ca71a-308d-47c7-ad44-41a2af1f9d36.json
> Adding SolarCyxity

- app_chains/e0a1a8e0-f617-4251-bdba-80bd08f18b98.json
> Adding Cyxerion

- app_chains/e329a81e-ada6-4b82-8e48-7e0e7543e373.json
> Adding MysticCyxx

- app_chains/ee1419b4-b31a-43d6-9ddb-36c81cc8e837.json
> ✨ adding naser

- app_chains/01ff512b-0260-46b0-9aaf-80fe56267d61.json
> Adding CyxelDust

- app_chains/fb4640d1-1f79-4db8-9dd9-68275b8b77cd.json
> adding meg0302

- app_chains/b878971e-fae6-4b5d-b56e-5cad0ec7e9ec.json
> Add meg9727

- app_chains/1f5de0f7-d73e-4f2e-a582-4edfefb200ff.json
> ✨ Adding zacnider

- app_chains/6ed70143-2209-4a1f-89b1-073dbbfffe17.json
> Adding kenshin

- app_chains/aa819ba3-d632-48be-8d75-7c3562f6a051.json
> ✨ Adding SATOSHISTART

- app_chains/615d042d-0943-48b1-b12e-b638704ea9aa.json
This is my first Avail AppChain named mrenwl2001madara
> ✨ Adding mrenwl2001madara

- app_chains/9317410a-fbf6-43be-9d47-1f64ddaebf48.json
> ✨ Adding kiln

- app_chains/ee7bc5ad-2b15-4af6-be43-94411e3ba6c7.json
> itakhost avail

- app_chains/3fa9301f-09b3-4490-87ae-e78f4881980b.json
- app_chains/d8856795-333e-4535-810c-5c090446ca9b.json
> ✨ Adding maj007

- app_chains/6c4b4d15-7655-4edb-9ef7-ec1a0dacbc46.json
> ✨ Adding innerverse

- app_chains/c58c8721-317d-4cde-aa78-894dae2715d1.json
This is my first Avail AppChain named son
> Adding AppChain son

- app_chains/35bf98b9-b351-4ae4-b8c3-7b3523a621a6.json
> adding traudien

- app_chains/541bdb21-2ecb-458e-8382-22f6f99d0c03.json
Adding specialfactor0 app chain
> Adding specialfactor0

- app_chains/ids.json
> ✨ Adding hafizhadim

- app_chains/0d05c2d8-fb1e-4660-856e-82fd31643ef7.json
This program is for isolating oracles
> Adding korosh

- app_chains/5525a6b5-a8c7-4efa-ae81-32da3b8aedea.json
> ✨ Adding melis

- app_chains/2ef3d7b4-9fee-4b8d-9378-1427fe9507f8.json
> ✨ Adding 0xlegend

- app_chains/ad3ee677-dd8a-4f12-9182-038f8d6ec255.json
This program is for isolating oracles and data
> Adding setayesh

- app_chains/1c8c6641-b8c9-4685-aab2-80ecdd0d3d0e.json
Mingo is the greatest app-chain on earth.
> ✨ Adding mingo

- app_chains/a385a7b6-1d91-4bdb-8c91-e5973bbb2e0d.json
> ✨ Adding therumi

- app_chains/51552e65-5e7b-4cc6-bdfb-f0c6c94dee25.json
Create 51552e65-5e7b-4cc6-bdfb-f0c6c94dee25.json
> ✨ Adding paragenies

- app_chains/d27868e1-0cf3-4c79-987a-e4c3b5c77c1b.json
> Adding pendulum

- app_chains/b08f510e-2200-4575-a324-dbb21495597c.json
> Adding 0xLei

- app_chains/13378101-6113-4c8a-affc-051eb3629322.json
This is my first Avail AppChain named nastybit
> Adding nastybit

- app_chains/d9c484ce-5d0b-40f2-a000-cd9d7182218x.json
> ✨ Adding AppChain bavo

- app_chains/474f07d5-e2c9-4176-b9ef-6b567f79e090.json
> ✨ Adding bekhorash

- app_chains/praktus/41e0b902-ff5d-4cdf-bfeb-3d6ec8f317d6.json
> 41e0b902-ff5d-4cdf-bfeb-3d6ec8f317d6.json Adding Praktus

- app_chains/e02409ec-ccca-4589-9755-ac2315549bc2.json
> ✨ Adding kiarash

- app_chains/753de0a4-68cd-4d63-8496-27eb55582c62.json
This is my first Avail AppChain, Horizon was created to contribute to the testing and development of Avail and its data availability.
> 🌅 Horizon 🌅

- app_chains/d01f3572-e2bc-4f43-af64-c8b1ade53a6b.json
- d01f3572-e2bc-4f43-af64-c8b1ade53a6b.json
avail madara app chain denemek
> ✨ Adding denemek

- app_chains/164b41b5-4b3e-4ec9-9ada-723e82bb748c.json
> ✨ Adding pepe

- app_chains/c7e689a0-b9e0-40bc-b819-9d5ce5dbecff.json
[c7e689a0-b9e0-40bc-b819-9d5ce5dbecff.json](https://github.com/karnotxyz/avail-campaign-listing/files/14215485/c7e689a0-b9e0-40bc-b819-9d5ce5dbecff.json)
> Adding cryptogang

- app_chains/12f8f6a7-cb35-4b3d-894c-bd31435a48e7.json
> ✨ Adding setin

- app_chains/a3abc94a-5349-426b-8140-e4d5d8344c47.json
> Adding Billion 

- app_chains/6e18337e-3959-4a63-9dce-c0d4b99ce31c.json
> ✨ Adding kurdgozar

- app_chains/1c00b386-19c8-4b00-96e3-f12b978f9301.json
> ✨ Adding CrypTolga

- app_chains/76e01623-ec7c-4c00-8fc2-d82760538526.json
Web social graph data analysis 3
> Adding story

- app_chains/dbbde36b-85df-4fa3-a4f1-50d510bb2f79.json
Web3 social graph data analysis
> Adding hiva

- app_chains/55553648-f791-423f-8bb1-a17d55287088.json
> ✨Adding onixia

- app_chains/cf800cb5-52b5-4f6d-990e-c8dd40bf2bc7.json
> ✨ Adding gmjoss

- app_chains/4bd28112-a60d-4db1-90e0-22513c1f7ff4.json
> ✨ Adding _twipZ_z

- app_chains/bff9dbfd-5bde-4f5d-9035-393039582381.json
> ✨ Adding vulcoinn

- app_chains/87eb987c-06b0-42d0-9736-c4d0f3d8466b.json
Avail-Madara / ConghcAppChainMadara App chain
> Adding ConghcAppChainMadara

- app_chains/05f13443-7cc6-406c-96c3-8e23afa18e0a.json
This is my first Avail AppChain
> Adding AppChain !!

- app_chains/5802de82-1dc6-48ef-8cfd-91552e996be4.json
This is my first Avail AppChain named zuri
> Add files vi✨ Adding AppChain zuri

- app_chains/a5c643bb-a47d-42b6-b464-3506b647bc90.json
This is my first Avail AppChain named zianlin
> adding zianlin

- app_chains/6dda65bb-2156-472d-bf0a-9145d9567c5e.json
This is my first Avail AppChain named shadowf
> 6dda65bb-2156-472d-bf0a-9145d9567c5e.json

- app_chains/111fd410-4204-4e97-a83d-9e5e949a59ea.json
> Adding truchain

- app_chains/e13b3a65-2884-4630-9f7b-db3ae47b43b7.json
Create appchain e13b3a65-2884-4630-9f7b-db3ae47b43b7.json
> adding kubull

- app_chains/ff1e0429-a8d7-4f80-9a6a-001fe1ba14bd.json
My first Avail AppChain "Hangoz"
> ✨ Adding AppChain Hangoz

- app_chains/ac1ba115-9e01-4514-a960-994d5cb18db0.json
> ✨ Adding cryptository

- app_chains/55798fc1-3616-47a3-99c5-acb2a7fe96bd.json
> 55798fc1-3616-47a3-99c5-acb2a7fe96bd.json

- app_chains/0a01eae4-1866-40f0-8674-949c3298cbbb.json
This is my first Avail AppChain named renmwl2002karnot
> ✨ Adding renmwl2002karnot

- app_chains/8f885882-b141-4cdb-86e7-73589122e45b.json
Adding `uchiwa` app-chain with id `8f885882-b141-4cdb-86e7-73589122e45b`
> Adding uchiwa app-chain

- app_chains/97314d53-a2e1-46c8-9fc0-60855424581c.json
> ✨ Adding mazi

- app_chains/ae97a38d-0d5c-4fe7-b325-2d82846b4121.json
This is my first Avail AppChain Arthazholic
> ✨ Adding AppChain Arthazholic

- app_chains/942ff35e-f048-4d10-ae61-6cb970cad2f0.json
Reverts karnotxyz/avail-campaign-listing#5400
> Revert "✨ Adding AppChain Pouria"

- app_chains/2a685d7e-ebc8-4efc-a45d-ea09e0baa4d9.json
This is my submission for the madara rollap
> Adding zrx

- app_chains/72774ed0-0221-46fd-8227-36852cd82282.json
updated new ip, ı lose old server access ı change with new ones
> ✨ Adding MelioBTR

- app_chains/d90ee69c-aedc-434c-acf4-d7275fff6f2d.json
> ✨️Adding milad6890

- app_chains/b01543db-9e08-4e46-8693-561b3801c3e5.json
> Adding mkh

- app_chains/f397326e-02c6-4ee1-b0f8-26ec70859618.json
This is my first Avail AppChain named milechain
> ✨ Adding AppChain milechain

- app_chains/7284ce09-74d1-4fc7-8a9f-75e278620c61.json
> ✨ Adding mojtaba

- app_chains/05757f2a-169f-4184-ab0d-74d22dcbfd4e.json
> ✨ Adding dada

- app_chains/fa348bd0-a999-4814-94cd-e7568aa6feaa.json
> ✨ Adding pashmam

- app_chains/63884a2a-0fa0-437e-9756-1837fac9751f.json
> ✨ Adding soltan

- app_chains/5937ec10-c81f-49a2-901e-0b7426a0be8b.json
> ✨ Adding elmon

- app_chains/c731bf3c-25e1-4657-bb65-2a9ccf41851f.json
> Adding Mjeyy

- app_chains/056b82f6-922a-419e-b377-8d141bd9d371.json
This is my first Avail AppChain named Sasuke
> ✨ Adding AppChain Sasuke

- app_chains/4cbb5b6b-6e52-4ab1-9e22-19d1d8466f56.json
This is my first Avail AppChain named wastie
> ✨ Adding AppChain wastie

- app_chains/e1b2ee25-82ce-4b04-b3f4-a290d710f6cf
- app_chains/e1b2ee25-82ce-4b04-b3f4-a290d710f6cf.json
> ✨ Adding Nesocial

- app_chains/1c6c5379-e234-4dc4-85be-91909126ba92.json
[1c6c5379-e234-4dc4-85be-91909126ba92.json](https://github.com/karnotxyz/avail-campaign-listing/files/14227963/1c6c5379-e234-4dc4-85be-91909126ba92.json)
> adding melon

- app_chains/88d37983-bbf4-4fd9-b601-d8904e2fbb44.json
This is my first Avail AppChain named jargo
> ✨ Adding jargo

- app_chains/beb88133-b55a-4b2d-81d7-4bdeb032b3bb.json
> ✨ Adding MrBTC

- app_chains/f68de334-4a3f-4476-aacc-35129e61e643.json
> Adding Ambatunat AppChain

- app_chains/306c62be-a1ce-4c7c-ac2e-73053b78da31.json
My First Avail AppChain hanetoy
> Adding AppChain hanetoy

- app_chains/81c392e4-fc27-4739-8f12-bdb0ee5106e2.json
> Adding purpleeyes 

- app_chains/f14a38e2-1df3-46dd-89c3-a7f727168ffc.json
This is my first Avail AppChain named snowman
> ✨ Adding AppChain snowman

- app_chains/addfa646-0df8-489d-af96-7e99308fc371.json
This is my first Avail AppChain named reinhaver
> ✨ Adding reinhaver

- app_chains/dac10806-28ef-4794-b469-e511e0d4d7f9.json
> ✨ Adding sookhtejet

- app_chains/e289db42-3df7-4d25-be04-237622f0ec19.json
> ✨Adding Elihadi

- app_chains/91e404ae-4e19-46a1-b18c-5a8a5769021d.json
this is my appchain for contributions to the Avail project
my appcahin name: arlansider
> Adding AppChain arlansider

- app_chains/5a173989-72ec-49d1-b2e1-7025ca13c8c1.json
> ✨ Adding MrCrypto

- app_chains/b618d934-de61-4acf-bdde-dc1d7da8ca52.json
> ✨ Adding adara

- app_chains/edb9085d-98f1-40eb-8ae2-d3f8f70058b7.json
> ✨ Adding jakob

- app_chains/02c4a96f-d237-489e-a3bd-512f52275ff1.json
> ✨ Adding kennode

- app_chains/7f977aae-0d54-4512-b1bc-652624ed7366.json
> ✨ Adding loganavail

- app_chains/88be8dc3-4ad5-4e0d-8355-50556bea691c.json
> ✨ Adding haleh

- app_chains/00cbccac-728e-4a26-b3d0-9315d19d991e.json
I am adding my first Avail Appchain name shochan for the campaign
> ✨ Adding AppChain shochan

- app_chains/9508bbf5-9975-4427-bb22-bc1ec697d592.json
> ✨ Adding didier

- app_chains/f63ff49c-f2b4-4d43-96d0-0f67da19aded.json
> ✨Adding sohham

- app_chains/36ea8192-173b-4933-bcd6-6c0c6af2c15f.json
This is my first Avail AppChain named joss
> ✨ Adding AppChain joss

- app_chains/f2d9dd74-f205-45a0-8d02-e610283ff213.json
[f2d9dd74-f205-45a0-8d02-e610283ff213.json](https://github.com/karnotxyz/avail-campaign-listing/files/14228647/f2d9dd74-f205-45a0-8d02-e610283ff213.json)
> Adding ShinLiquid

- app_chains/0724e7c8-127f-4298-a5b8-18b9a50d924e.json
> Adding nbx2y2

- app_chains/2708ca53-2455-48a9-87c6-7c3abe6e5572.json
> Adding CyxaraNova

- app_chains/e321d7f1-2def-4aca-9e16-cac7e55fba96.json
> Adding QuantumCyx

- app_chains/a1bb1134-e8e7-41ef-a4f5-7305250ef570.json
> ✨ Adding mohammad9066

- app_chains/cce8c6a1-8310-459f-94aa-2c3edb50bcf4.json
This is my first Avail AppChain joko
> ✨ Adding joko

- app_chains/2ff5ea77-cd78-4a22-8791-99d9325149b3.json
> ✨ Adding avail1

- app_chains/c20ad1bc-2750-4244-8b36-5ab4853e1e1b.json
> ✨ Adding arash60

- app_chains/a1c95aaf-5cec-47e1-9dcb-6bbeee345654.json
> ✨️Adding gmexnode

- app_chains/b7aafa60-2073-4805-aab2-482b9609d7d7.json
[b7aafa60-2073-4805-aab2-482b9609d7d7.json](https://github.com/karnotxyz/avail-campaign-listing/files/14229298/b7aafa60-2073-4805-aab2-482b9609d7d7.json)
> Adding Kourosh_Hamdi

- app_chains/184431f4-dc04-4225-a255-9d7c7497fa31.json
> Adding noureasy

- app_chains/2f3ec3d0-5197-4bb2-9388-038be4c33b7c.json
[2f3ec3d0-5197-4bb2-9388-038be4c33b7c.json](https://github.com/karnotxyz/avail-campaign-listing/files/14229032/2f3ec3d0-5197-4bb2-9388-038be4c33b7c.json)
> Added citexnode

- app_chains/866720db-7be6-41ce-b62f-2992452298f5.json
> ✨️Adding hajreza

- app_chains/1b61bc6c-1bf2-444e-9b12-636f64b6b7b3.json
> ✨ Adding 0xdemon

- app_chains/326ef3ef-fa1c-4e0a-9f27-aaedb593c700.json
> ✨ Adding grayBoss

- app_chains/be34eb50-2ee3-41f8-8d4d-5da0daa99952.json
This is my first Avail AppChain named boss
> ✨ Adding AppChain boss

- app_chains/3ab638b2-bf34-4f4f-8837-50d9a0e74311.json
This is my first Avail AppChain named madara
> A✨ Adding AppChain madara files via upload

- app_chains/4a87300a-a5f7-4ba2-8323-2bca03d5148c.json
> ✨Adding ermia

- app_chains/b643a021-dbd6-4d7f-acfa-6933ab4e9d2c.json
This is my first Avail AppChain named dosukoi
> ✨ Adding AppChain dosukoi

- app_chains/d407ee98-dc91-4058-8854-5fad42753adb.json
This is my first Avail AppChain named shorta
> ✨ Adding AppChain shorta

- app_chains/3ff3d9e5-4ed4-4de7-aff7-ede44a93e587.json
> ✨Adding chain kirara

- app_chains/61d6b87c-c8a9-48b4-acd9-c12b7b6aea8d.json
This is my first Avail AppChain named konoha
>  ✨ Adding AppChain konoha ✨

- app_chains/4b2ca6a4-774d-43f3-984d-71bcc3d9603c.json
This is my first Avail AppChain named thefak25
> ✨ Adding thefak25

- app_chains/82fde3db-063f-421f-ae70-a6fb9acd20a5.json
This is my first Avail AppChain named juAhn
> Adding AppChain juAhn

- app_chains/5e62c08f-6148-4742-827e-d0747653ee28.json
This is my first Avail AppChain named 0xmashiro
> ✨ Adding AppChain 0xmashiro

- app_chains/0e12053c-a90b-41d2-bef8-0dc049f7b169.json
avail-campaign-listing_Beemadara
> Adding Beemadara

- app_chains/2b472474-4417-4ede-ac57-44e4adcd4660.json
> ✨ Adding dipsi

- app_chains/971c870c-f16e-4fb1-846a-782e36244096.json
This is my first Avail AppChain named aurora
> ✨ Adding AppChain aurora

- app_chains/5130a753-1fb4-4c16-9ccd-c8a6471a9cc1.json
This is my first Avail AppChain named Bubbleburst
> ✨ Adding AppChain Bubbleburst

- app_chains/038037fc-211a-4243-898e-cb270ac5c29b.json
This is my first Avail AppChain named Mou
> ✨ Adding Mou

- app_chains/f1a54415-faa9-4c6e-b8a8-f5ac6562adf2.json
This is an application to integrate Oracle Redstone with Social Graph
> Adding morph

- app_chains/910fd085-4fe4-43a7-ac4b-9b7518694b69.json
> ✨ Adding padra

- app_chains/7e2025a9-7678-46dc-9159-8ff6533e3778.json
> ✨ Adding kaisuhan

- app_chains/677c2f6a-1c9b-45b2-aacc-223e8ae1ffb4.json
> ✨ Adding AppChain dhozil

- app_chains/ebe51c72-8d1a-474d-af84-14a9aa6d1153.json
> ✨ Adding stephanie

- app_chains/333dff74-7017-41c8-a955-67f581d9679e.json
> ✨ Adding babayagabul

- app_chains/681ed8dc-0214-4971-8f80-31da563819a8.json
> ✨ Adding Aladeen11

- app_chains/c4898e44-571f-4b15-aaab-ac3fce306847.json
> ✨ Adding sirhoney

- app_chains/64095a38-41a0-4e88-8bef-41ec53fcff92.json
> ✨ Adding Parcham

- app_chains/3957f7dc-0f0f-4eea-b2c7-f49839f37fda.json
> Adding pempeklahat 

- app_chains/46399efa-c32e-494a-b23e-17bf47f022f0.json
This is my first Avail AppChain named olatuyitony
> ✨ Adding AppChain olatuyitony

- app_chains/586b016d-d62d-4ae9-acae-a1aae37c9dbd.json
This is my first Avail AppChain named madara
> ✨ Adding madara

- app_chains/503313d4-2003-4eb7-a860-e4540f0972a9.json
Adding an app chain with the important details in the JSON file.
> ✨ Adding okpokoemel

- app_chains/63388a44-e396-4f1e-b28f-fea5a9562a71.json
I had to try again as my VPN had issues. Locked and ready to go.
> ✨ Adding gsever

- app_chains/43f5a214-8b23-4dd3-954f-f8e9b7084549.json
my first AppChain on Avail Madara
> ✨ Adding AppChain mabera

- app_chains/016952e9-7a3c-420f-aeb8-1c55e70f3b8d.json
> wonameguai

- app_chains/1a13771c-9aa0-432e-8591-f32a075fab01.json
This is my first Avail AppChain named soulman
> ✨ Adding AppChain soulman

- app_chains/de704a40-47fc-449d-8525-f21ad08a65d2.json
> ✨ Adding Adeoniye

- app_chains/609efc53-3443-4554-a0ec-a9bb52b3d0ee.json
> ✨ Adding farzan

- app_chains/11765db8-f4c4-4b6b-a507-4e6f19427d48.json
> ✨ Adding m0h5en

- app_chains/386afe12-d43a-44cf-8b19-0cba72a3ea3a.json
> ✨ Adding DeadsGod

- app_chains/72120f42-9b28-4eae-b889-7b84ee3b526d.json
I'm adding a new app chain with all the relevant details in a JSON file located inside the app-chains folder.
> Adding "Papichulo447"

- app_chains/ab7123de-77f8-419b-8354-c2accfdfd68a.json
> prettier pass

- app_chains/a207b499-e0f6-423e-a22d-79b09a32a179.json
This is my first Avail Appchain
> Adding wizzy

- app_chains/6c98d3cb-70ee-4270-9f15-a1f0ce18bc20.json
Adding a new app chain by adding all the relevant details in a JSON file inside the app chain folder.
> ✨ Adding Joespaz

- app_chains/f8427caa-2a94-47da-89cb-5b3d52a5b89c.json
> ✨ Adding poetrist

- app_chains/186ef5fd-416b-4143-9e24-935c605fc66d.json
> 186ef5fd-416b-4143-9e24-935c605fc66d.json

- app_chains/f0b8c161-3b45-4e74-8772-c5647413c5e5.json
This is my first Avail AppChain named dedek168
> ✨ Adding dedek168

- app_chains/e4115b4b-b662-4248-b601-d0b0f2484d5f.json
> Adding mtfvkk

- app_chains/015c47dd-1a26-45d9-913c-c41a602264d3.json
> ✨ Adding tchain

- app_chains/9e934fc5-0416-4465-b427-4e6d4002b3c2.json
This is my first Avail AppChain named bucchi
> ✨ Adding AppChain bucchi

- app_chains/2989a54f-cf0a-4db6-8471-60dbb181d101.json
> ✨ Adding slattingoo

- app_chains/664b02b7-2259-43cf-9c1c-24019521b8c5.json
> ✨ Adding pangoan

- app_chains/13884541-a46f-4c25-a139-035a8115e594.json
This is my first Avail AppChain named adya
> ✨ Adding AppChain adya

- app_chains/3c0116f4-cd7a-4251-aa64-69187d1edeac.json
This is my first Avail AppChain named rotijahemerah.
> ✨ Adding AppChain rotijahemerah

- app_chains/4f71e199-94fb-4598-87c8-f2d08faaffd0.json
> ✨ Adding ymittal_playground

- app_chains/765ffd85-e10c-40b9-9bc5-a69137c7d15f.json
This is my first Avail AppChain named smeby
> ✨ Adding AppChain smeby

- app_chains/2c26901a-dd6f-4905-9b07-62f9b1ef736b.json
This is my first Avail AppChain named tatiana
> ✨ Adding AppChain tatiana

- app_chains/80d97165-e660-4058-a8cc-945d44dbc337.json
This is my first Avail AppChain named memeda111
> ✨ Adding AppChain memeda111

- app_chains/0fea6f5f-7b8d-4f00-b95b-5b90f3415f66.json
> ✨ Adding AppChain Kevil 

- app_chains/8a85f7c9-c189-4c49-b2d6-9cea7309de17.json
This is my first Avail AppChain named tanim
> ✨ Adding AppChain tanim

- app_chains/3c8c3264-2bb2-4255-99ce-cce4f26add9e.json
> Adding ykniggemadza

- app_chains/2e13889d-ab4a-4753-ab38-11145bbcf15f.json
> :sparkles: Adding okanm

- app_chains/fc09eb1a-cf3d-4d07-94d3-4aa642cb1b5d.json
> ✨ Adding LandB

- app_chains/490db9df-3cae-49f3-b425-c624bb7d577e.json
This is my first Avail AppChain named jimat
> ✨ Adding AppChain jimat

- app_chains/639a8be6-6d79-4531-a255-58310a960747.json
> ✨ Adding vichain

- app_chains/bb4ecd16-547a-4bcd-9e3f-e1a98b7e455d.json
This is my first Avail AppChain named fahira
> ✨ Adding AppChain fahira

- app_chains/8ccb0843-ee54-4b19-a79f-ae70291257e6.json
This is My First Avail Appchain named Madarast, 02/11/2024
> ✨Adding Appchain Madarast

- app_chains/3e48e4b8-0300-41b3-a535-4745768091fe.json
> ✨ Adding WojaK

- app_chains/40ea89e0-30bc-4580-a3f2-b8c1f3a9dbef.json
> ✨ Adding mrbabit

- app_chains/930fa5a8-8c45-494d-ab12-cbc0c005bfe5.json
This is my first Avail AppChain called kttaang
> Adding kttaang

- app_chains/f3e3b3d1-8b5e-4297-b564-63b3e9fc3dcf.json
> ✨ Adding miladeos

- app_chains/600b1906-b0ce-4392-a6fb-8eb61edaac7a.json
> ✨Adding dakochan

- app_chains/ffd3503e-19ab-4a17-a3f2-1ef87ba8d882.json
> ✨ Adding AppChain Yousuph

- app_chains/f8111ae4-44c7-4d04-a62d-4cdbe81a4588.json
Program for Deep Linking Neural Intelligence with the Web 3
> Adding rez

- app_chains/798af595-3329-4e0b-b16c-efe5177fbaee.json
>  ✨ Adding Umitayhan

- app_chains/8ca06596-8370-45a4-b55f-48545bbeed85.json
This is my first Avail AppChain named geboy
> ✨ Adding AppChain geboy

- app_chains/d268dece-9887-4481-97d4-aa835e66ccd1.json
> ✨ Adding Shavail

- app_chains/2aef851a-5572-4265-89bb-93145e07c703.json
> ✨ Adding ekmek

- app_chains/c6f5ff98-5b59-4902-ae68-8c9f1f4f0377.json
> ✨ Adding Availvision

- app_chains/acac1265-07f5-4984-b76b-c516313ff7f3.json
This is my first Avail AppChain named luckyv
> ✨ Adding AppChain luckyv

- app_chains/042579f5-91e6-4360-ad2a-c447016aabbd.json
> ✨ Adding jablai

- app_chains/cf76f1d8-8e32-49f0-af7d-e3eaeb0d1f97.json
This is my first Avail AppChain named ilaNihas
> ✨ Adding AppChain ilaNihas

- app_chains/0bb95d11-7a19-42b1-b819-80fc7f7498ff.json
> ✨ Adding AppChain Nokia

- app_chains/a9f7e5c0-0d76-4ea0-9a43-fe2544d41526.json
This is my first Avail AppChain named rezarwz
> ✨ Adding AppChain rezarwz

- app_chains/4022f90a-6382-4ca2-95d6-2c3ea8c3e46a.json
> ✨ Adding Motela

- app_chains/00db46ce-050c-4735-a3ea-83a5082eeced.json
This is my first Avail AppChain named frankiee
> Adding frankiee

- app_chains/eed8fea6-e18f-4f7f-bddd-893e6054722b.json
Adding a new app chain by adding all the relevant details in a JSON file inside the app-chains folder
> Adding 'ihsandgn'

- app_chains/03eda5fc-9aa5-4163-b924-7c4def70975b.json
This is my first Avail AppChain named mcgee
> ✨ Adding mcgee

- app_chains/3026123f-1c7e-460c-84e9-34895eef6784.json
- app_chains/326583c5-e8c6-449a-9848-e1f4ab3d4c0a.json
- app_chains/640c2a86-4f48-4776-93c7-541fe98385db.json
- app_chains/94cb29f9-2269-45d0-b442-e6690a6d7a24.json
- app_chains/dd2f832b-0cff-46f6-909d-574ef8567e39.json
This is my first AppChain named YUGO
> ✨ Adding YUGO

- app_chains/5e1b8b43-ff4f-45bb-a8fe-7814fe5a03bc.json
Adding an app chain with the important details in the JSON file.
> ✨ Adding 0xbitz

- app_chains/57581b75-7346-4c8a-912a-1f8d4780fd9d.json
> ✨ Adding mahgerman

- app_chains/24d76c90-330f-43ca-9ddb-53ad803e86e3.json
This is my first Avail AppChain named ZTV
> ✨ Adding ZTV

- app_chains/b5aff922-8133-4882-a7d4-a2081c2c3a84.json
This is my first Avail AppChain named dangerdawg
> ✨ Adding dangerdawg

- app_chains/67627010-ce6c-4336-b0ad-4b7a3994e8cb.json
> ✨Adding shawnkelz

- app_chains/26f9e532-f02e-40d7-a78e-108dd3acc410.json
This is my first Avail AppChain named donatmanis.
> Adding AppChain donatmanis

- app_chains/feb4b533-4fae-465d-8100-bafcd91cd61c.json
> ✨Adding waymaker

- app_chains/5319abb4-1025-4db3-8bf7-526bf51f3f66.json
This is my first Avail AppChain named ArnoldCNS
> dding AppChain ArnoldCNS

- app_chains/58b7a559-26d2-425c-ae78-ec373097f7da.json
> ✨ Adding mrsurmeli7 

- app_chains/dcf376c2-ca86-417c-a42b-427be874a248.json
> ✨ Adding planetpload

- app_chains/a064ac58-61c8-4fcc-baa1-74eb3cad672b.json
> ✨ Adding damoncrpnode

- app_chains/8d719df1-3d75-4b3c-a758-f5bc9e218acb.json
[8d719df1-3d75-4b3c-a758-f5bc9e218acb.json](https://github.com/karnotxyz/avail-campaign-listing/files/14233258/8d719df1-3d75-4b3c-a758-f5bc9e218acb.json)
> adding mahsa

- app_chains/3ba4484f-9ae2-4cf6-a344-3224cebcb415.json
> 3ba4484f-9ae2-4cf6-a344-3224cebcb415.json

- app_chains/9b754547-d9ef-4347-9b9d-b5cc4a96953f.json
> ✨ Adding ulshames

- app_chains/b2b690e6-aafd-4774-865e-5ffff5fa963a.json
> ✨ adding saeedkatana

- app_chains/863b8a62-c915-11ee-a506-0242ac120002.json
[863b8a62-c915-11ee-a506-0242ac120002.json](https://github.com/karnotxyz/avail-campaign-listing/files/14233825/863b8a62-c915-11ee-a506-0242ac120002.json)
> ✨️Adding 0xhabib

- app_chains/61a10ffb-98e0-468e-a682-1b400f0a01fc.json
this is my first appchain, named iblitzc0de
> add iblitzc0de appchain

- app_chains/ad8403f0-8d8d-42d2-a062-b8dd49d184f0.json
This is my first Avail AppChain named Yogicz
> ✨ Adding Yogicz

- app_chains/c002612a-73ee-4fe0-a240-fb4ec8465b37.json
> adding cihatoz

- app_chains/74b0ee8b-102b-4302-919d-1016359b84b8.json
This is my first Avail AppChain named dosbaa
> ✨ Adding AppChain dosbaa

- app_chains/bdaf03f8-fa75-4988-8a9d-7bb3e989f271.json
Reverts karnotxyz/avail-campaign-listing#8912
> Adding oxhojat

- app_chains/2516985a-a07a-4564-8a95-43615ff1742c.json
This is my first Avail AppChain named agungryzm
> ✨ Adding agungryzm

- app_chains/16d312bc-b148-4cc0-9a24-016eb98035ea.json
> ✨ Adding berhadiah

- app_chains/4a0bc46b-7e09-4562-aa0d-40c4ca28a6e6.json
[4a0bc46b-7e09-4562-aa0d-40c4ca28a6e6.json](https://github.com/karnotxyz/avail-campaign-listing/files/14234376/4a0bc46b-7e09-4562-aa0d-40c4ca28a6e6.json)
> Adding bigmorad

- app_chains/0401852a-4038-42ac-bf83-425030a52f49.json
- app_chains/a20d18d5-f78d-4907-a923-2db404c240c4.json
This is my first Avail AppChain named Geonoder
> ✨ Adding AppChain Geonoder

- app_chains/0729d67e-aac7-4b47-9d40-e145980eb150.json
> ✨ Adding iseng

- app_chains/992ca982-18d3-437b-bd6f-cc36e438c3a3.json
Adding a new app chain by adding all the relevant details in a JSON file inside the app-chains folder..
> Adding zardozmonopoly

- app_chains/6d1b8736-b5ec-479c-b362-b52bcaad47fc.json
This is my first Avail AppChain named xonenode
> ✨ Adding xonenode

- app_chains/f0b09943-fe3e-4a59-aa0d-e79bcde1f7be.json
This is my first Avail AppChain named sukses
> ✨ Adding AppChain sukses

- app_chains/8b9e6fdf-4325-4dca-abfb-339fb23ac814.json
This is my first Avail AppChain named clive998
> ✨ Adding AppChain clive998 

- app_chains/e7858136-ecdf-49e9-82f3-9386786e060c.json
This is my first Avail AppChain named dyana
> ✨ Adding AppChain dyana

- app_chains/0685445b-dee4-43d1-b57a-3e0a38f39771.json
This is my first Avail AppChain named selow
> ✨ Adding AppChain selow

- app_chains/fc0f50eb-a2dd-4b76-92fb-4c2fbb634680.json
This is my first Avail AppChain named donkrieg
> ✨ Adding AppChain donkrieg

- app_chains/403f1eb4-d5c8-4de7-8624-e231d1a329cc.json
403f1eb4-d5c8-4de7-8624-e231d1a329cc
> My first one

- app_chains/bb09b9f2-a2ad-47d0-b2a1-aad1717141c8.json
Adding a new app chain by adding all the relevant details in a JSON file inside the app-chains folder
> ✨ Adding 'hodlstory'

- app_chains/d6e614eb-bf22-4927-8674-fa104ca72b1a.json
first appchain from andalusia1337
> first appchain

- app_chains/6c3516f9-a2b7-403d-88d1-b641d7e1c188.json
This is my first Avail AppChain named amirdrop
> ✨ Adding AppChain amirdrop

- app_chains/2cc4ca2b-5a3c-481c-812c-fec644e7aea0.json
This is my first Avail AppChain named hyogoro
> ✨ Adding AppChain hyogoro

- app_chains/798ebbdc-2f23-4d04-a2c7-fbce9d7f4893.json
this my first appChain Avail named Gungzzavail
> Adding Gungzzavail

- app_chains/4e2b9131-8004-4281-980a-747fc47414ee.json
This is my first Avail AppChain named pikal
> ✨ Adding AppChain pikal

- app_chains/5806ce4a-5d83-460f-840a-921c2781cd1c.json
>  ✨ Adding AppChain bitmojin

- app_chains/7e3076c8-5e4a-4c76-8a4b-c388d60d60d2.json
This is my first Avail AppChain named mantap
> ✨ Adding AppChain mantap

- app_chains/075dc110-5e3e-4d92-b6bc-5636ab34f2b7.json
This is my first Avail AppChain named woody
> ✨ Adding AppChain woody

- app_chains/160da5ff-a369-4688-94d2-0320ef0a76a2.json
This is my first Avail AppChain named mori
> ✨ Adding AppChain mori

- app_chains/baf3eaa4-0cf2-48dc-9f5a-0d0fef26cef0.json
This is my first Avail AppChain named koba
> ✨ Adding AppChain koba✨

- app_chains/82c82d78-2953-4029-9c2f-1929be1aa6e2.json
This is my first Avail AppChain named sato
> ✨✨ Adding AppChain sato

- app_chains/d0cbd5f8-e3b2-4020-a031-9e64e1c84bb5.json
> ✨ Adding amytis AppChain

- app_chains/8cdc1078-8b1d-4db8-8db8-48e98c40aa72.json
> adding rice app

- app_chains/858f2edd-e18e-4887-bf50-185d8cac43c6.json
This is my first Avail AppChain named melly
> ✨ Adding AppChain melly

- app_chains/4a2f1cc3-649c-4a07-8055-1ff19c37e7d1.json
This is my first Avail AppChain named dontbemad
> ✨ Adding dontbemad

- app_chains/000170c5-5bce-41a2-8e97-e128f1d7781a.json
> ✨ Adding aghamasmass 

- app_chains/e9d5ca9f-dc21-4b4a-acaa-242a3eb242df.json
> ✨ Adding nguyenhungtuan

- app_chains/9e4968b3-6da9-4dee-a6fb-e8019e9e1ac1.json
This is my first Avail AppChain named mengnan
> ✨ Adding AppChain mengnan

- app_chains/a2e57375-ecf4-4104-a9b6-9c4d66679864.json
> ✨ Adding MEH2

- app_chains/90648754-2ed5-4af4-8f40-995583c37f85.json
> ✨ Adding Ruska

- app_chains/10bd6875-809d-4efb-8da6-55ed94cdbdf6.json
This is my first Avail AppChain named “MissUU"
> ✨ Adding MissUU

- app_chains/bb9af96d-e095-481f-8e24-c0bb0d58a84e.json
This is my first Avail AppChain named
> ✨ Adding AppChain mandleer

- app_chains/acd3e6a1-25b1-45a4-86d5-16516e7d0cfc.json
> ✨ Adding aranx

- app_chains/fe8a66aa-89f8-4aa8-83ba-6b20b7bfdf0a.json
> Adding qpc666

- app_chains/490dae90-ff12-4756-905e-309f7ea802b6.json
Adding a new app chain by adding all the relevant details in a JSON file inside the app-chains folder
> Adding moopig

- app_chains/a2053248-741e-4f4b-bce6-0ade074d5501.json
This is my first Avail AppChain named arean
> ✨ Adding arean

- app_chains/2f9778f2-dcdc-4ce1-8837-1eb13ae6f85b.json
This is my first Avail AppChain named PengavailTEST01
> ✨ Adding AppChain PengavailTEST01

- app_chains/f43a993f-ffac-44df-bb4f-0a52ae4f77a7.json
This is my first Avail AppChain named hendryfan
> ✨ Adding hendryfan

- app_chains/fe9a6b6f-d6a6-468e-8972-d04059fc9a9f.json
> ✨ Adding hassan1989

- app_chains/9dbc954f-9608-4497-b142-357e89bdad8f.json
> ✨ Adding frsoci

- app_chains/5d3b872b-0e5a-4aca-aa50-d0e03f32a131.json
> ✨ Adding XUmeme

- app_chains/2e664c12-3aae-4389-834e-53c32c4f1704.json
This is my first Avail AppChain named BETRIX
> ✨️Adding BETRIX

- app_chains/ca08d19d-9f49-4e7f-809d-b50e8694154f.json
This is my first Avail AppChain named malams
> ✨ Adding AppChain malams

- app_chains/38997da8-5bf0-45c3-8b17-7f0d5dbd7036.json
This is my first Avail AppChain named kuzDex
> Adding kuzDex

- app_chains/d7a2b790-e642-4b70-a78c-f2afd3c724cb.json
This is my first Avail AppChain named siskaa06
> ✨ Adding AppChain siskaa06

- app_chains/951a5608-9db3-4032-8a5b-bc273a3e3284.json
> ✨ Adding hosseinamm

- app_chains/1628b3a1-c357-4609-bc02-06bb728d615c.json
This is my first Avail AppChain named madamamba
> ✨ Adding AppChain madamamba

- app_chains/0aac25cf-5784-474f-b603-0e668f2afe32.json
> ✨ Adding ATOM

- app_chains/923d7557-5bdb-44cf-a268-b104bc034aca.json
> ✨Adding Ramsey

- app_chains/38c6d6ec-369a-4ba8-a632-1db585f5a638.json
This is my first Avail AppChain named candysand
> ✨ Adding AppChain candysand

- app_chains/88e30875-1775-4e4b-a92d-7e32d73cc4b1.json
> Adding worichers

- app_chains/64b96e8d-3faf-4b1d-9219-83467a51cfce.json
This is my first Avail AppChain named yangyang
> ✨ Adding AppChain yangyang

- app_chains/178dd1f0-2519-49da-bf78-8ccc73892290.json
> ✨️Adding meaw202

- app_chains/bfc4e8eb-f263-4fa7-a722-8307f2c8bc32.json
> Adding puxonisme Appchain

- app_chains/e1901518-9a8a-4e1a-9f5c-455e179c9e9b.json
> Adding reang0x appchain

- app_chains/353edf63-917a-4a8c-8148-03fdd70569db.json
> ✨ Adding shahanAdd files via upload

- app_chains/387a6d7e-cad3-4419-96c0-5d4d43fcd6e5.json
This is my first Avail AppChain named zyzy
> ✨ Adding AppChain zyzy

- app_chains/cc3561b6-a58b-47bb-8b95-a4b71c3764c7.json
This is my first Avail AppChain named ediology
> Adding AppChain ediology

- app_chains/abb7e50a-f22b-4db1-a19e-01a9ae913f11.json
> ✨ Adding supervail

- app_chains/e2877efb-bd13-44af-be9f-5ebe9eee13c5.json
My 1st appchain using Avail DA
> Adding Avail DA appchain Ekota

- app_chains/9a3d18b7-071a-40e2-94b6-565796d84fb5.json
This is my first Avail AppChain named alinakub
> ✨ Adding AppChain alinakub

- app_chains/5190bbe7-fb6e-49b2-8274-352f596c5641.json
> ✨ Adding zerion

- app_chains/86e8ecff-35e3-454e-ac78-b633d89d5b36.json
> adding construction

- app_chains/e339a61d-76bb-43a7-bd46-c263a0f7846c.json
> ✨ Adding barana

- app_chains/3d92384c-1dfd-4c3d-a2be-f9a33c2c8f55.json
> ✨ Adding elektriknode

- app_chains/e75c4cfd-f7ea-4c51-89ad-d8fe649c9300.json
> ✨ Adding moyo

- app_chains/7eda128f-8ff5-4b1b-96ea-ce4ea20a4dc4.json
> ✨ Adding utku58

- app_chains/b750809d-c780-4c3f-8190-72291bfc183b.json
> ✨ Adding bitnexst

- app_chains/d1728724-1bce-4e57-a2c4-3eac4b6370b7.json
> ✨Adding knode

- app_chains/f1e7f3b8-98f0-446b-9331-8997af131b58.json
This is my first Avail AppChain named YUGO
> Adding YUGO

- app_chains/16cea3ab-4401-4490-8281-cdad121027ec.json
> Adding devilspain

- app_chains/5105a097-50ef-4ed9-b039-4b0106818958.json
> ✨ Adding finegold

- app_chains/6f4fb4ba-f2fc-4dec-95b7-a5d00141e97a.json
This is my first Avail AppChain named firetoken
> ✨ Adding firetoken

- app_chains/89995964-febf-43a4-9f26-098f98317e9f.json
>  ✨ Adding carbon

- app_chains/9ae2cb3a-b118-45cc-9081-a96f399f25cc.json
> ✨️Adding pavlov

- app_chains/395a3cbb-023d-4e22-bc9e-e1b94e827394.json
Dtrung appchain using DA by Avail
> ✨ Adding AppChain dtrung

- app_chains/716a967e-74c5-4c97-b3fb-7402d574fec6.json
Adding a new app chain by adding all relevant details in a JSON file inside the app-chains folder.
> ✨ Adding mgakifMadara

- app_chains/7a901d2a-b7a7-47b3-bc47-d9a6de24a3d8.json
> ✨ Adding kocasinan

- app_chains/e831679b-7b5d-4ea5-bd5c-944626b2a024.json
This is my first Avail AppChain named lafei
> ✨ Adding AppChain lafei

- app_chains/38c6a0b0-a0ce-4a39-863f-ce8ebb1602f2.json
[38c6a0b0-a0ce-4a39-863f-ce8ebb1602f2.json](https://github.com/karnotxyz/avail-campaign-listing/files/14232543/38c6a0b0-a0ce-4a39-863f-ce8ebb1602f2.json)
> Adding leo

- app_chains/31495135-aa13-44df-83b2-25d2d1095f92.json
> Adding LHBlockAvail

- app_chains/ae61eca6-969e-4f20-a5e6-feb23fc4ba41.json
> ✨ Adding amiralek

- app_chains/b001a26e-408d-4fa2-b057-b7e2a3f120cb.json
> ✨ Adding bitban

- app_chains/d74733c2-aa80-4fb5-9fb7-1483bdd081d9.json
This is my first Avail AppChain named chandler
> ✨ Adding AppChain Karthik

- app_chains/ce30f9e2-19d6-462c-9dd8-808976a054ff.json
> ✨ Adding mehdito

- app_chains/778c6661-4faf-4a96-a5ee-c542ffd2cca8.json
> ✨ Adding mershad

- app_chains/edb94d7b-4d1c-4602-9e4b-ef5e3ab043be.json
> EsiN rollape

- app_chains/6db8d027-cef0-4d5e-a245-b3f362bebbb9.json
> ✨ Adding gazi

- app_chains/a7280af3-2195-41c8-84ec-90644413ee7d.json
> ✨ Adding x0bull

- app_chains/bc4627bf-e667-40b3-b919-e57012767f0a.json
> ✨ Adding kriptokenan

- app_chains/d632704a-a18f-4bff-9fb2-864d4b37ddb7.json
> baggervance app chain

- app_chains/1d169acd-89dd-4189-8709-6f53d1f7ecb3.json
my app-chain with AvailDA yesssssss
> ✨️Adding z3uzS

- app_chains/51bd62e4-b786-4b53-a154-3a04f908696c.json
> ✨ Adding Crypton

- app_chains/7583e518-cba8-4354-b15f-c94b7aeb6ede.json
> ✨ Adding ali

- app_chains/1d1c3759-9c94-4498-b84f-56bfe27cd94b.json
> Add daraei

- app_chains/f92c6667-a48e-4071-be45-aec844cc80c4.json
This is my first Avail AppChain named Kiriigami
> ✨ Adding AppChain kiriigami

- app_chains/958f24c5-fcab-42cc-bfd2-83c55f9efee6.json
> ✨ Adding Milad

- app_chains/2ee2ffa0-65d3-4976-a796-d58c52c894a6.json
This is my first Avail AppChain named mclachsss
> ✨ Adding AppChain mclachsss

- app_chains/8fb5af67-ca98-49cb-80f3-e0728725f544.json
Create 8fb5af67-ca98-49cb-80f3-e0728725f544.json
> ✨ Adding kerriwyllie

- app_chains/2f008ce5-b11d-491c-b801-2c82b02692bc.json
Create 2f008ce5-b11d-491c-b801-2c82b02692bc.json
> ✨ Adding mccaffertynyla

- app_chains/1ffc3068-3407-4230-b5d2-bcb6e30678f3.json
Create 1ffc3068-3407-4230-b5d2-bcb6e30678f3.json
> ✨ Adding minettaka

- app_chains/a7350677-f702-4dee-95bb-a08e22ea074f.json
Create a7350677-f702-4dee-95bb-a08e22ea074f.json
> ✨ Adding phelpskaren

- app_chains/4e53a121-098e-4082-a3e3-913df572e9d7.json
> ✨ Adding mrnobody

- app_chains/a513cd16-819d-45d3-9fbf-5a4d297996af.json
Create a513cd16-819d-45d3-9fbf-5a4d297996af.json
> ✨ Adding r9kzam

- app_chains/fbb44219-3e02-4f2b-aab4-ed5c01bd33f5.json
This is my first Avail AppChain named Nua
> ✨ Adding AppChain Nua

- app_chains/57d9e4f4-4466-4b57-a577-48f9d302e58e.json
Create 57d9e4f4-4466-4b57-a577-48f9d302e58e.json
> ✨ Adding ybhtwert

- app_chains/08af2074-941d-4520-ba7c-a4847cdfd738.json
> ✨ Adding exan

- app_chains/664038a3-8141-4af7-8bde-69d3d5f08f2a.json
This is my first Avail AppChain named cyn
> ✨ Adding AppChain cyn

- app_chains/afa8d310-248a-4d02-b932-a383fae68d7d.json
> ✨ Adding shakilagh

- app_chains/a2e9f4d8-62a0-4b78-b3ab-4dfe1b970754.json
> ✨ Adding navid1

- app_chains/3d24626c-67f5-4c5c-94b1-26f365c3a9e5.json
> ✨ Adding lesican

- app_chains/7fdf018d-4572-449d-9a47-c6b371effb44.json
> ✨Adding boss

- app_chains/c6359739-72d8-43c8-8ca5-46d61c6e336a.json
> node nespo383

- app_chains/7b066950-0efd-4006-af46-acfabd4670e0.json
> Add Ethernal 

- app_chains/554199d4-aca1-4b03-a584-a224cee322aa.json
This is my first Avail AppChain named 吊毛
> ✨ Adding AppChain 吊毛

- app_chains/af3710af-385b-4cf1-8107-70a624dbd69e.json
> Adding parisam

- app_chains/27ec21a5-9630-4675-bb16-0c13bcecb2c7.json
> Adding CyxenGlade

- app_chains/8a25b9f8-cf79-4ab0-bff5-2721f096da59.json
This is my first Avail AppChain named shironeko
> ✨ Adding AppChain shironeko

- app_chains/e98c6238-83e5-4927-b776-bcabae910f60.json
> ✨Adding Unlimitedwalliy

- app_chains/a7124e3b-68f5-4a99-8bba-5925a41ba221.json
> ✨ Adding 'Arcant'

- app_chains/a7124e3b-68f5-4a99-8bba-5925a41ba221.json
> Adding 'ArcanT'

- app_chains/b95a0b34-e4f4-4a9c-a389-cfcfe35b5642.json
> Adding "timmy"

- app_chains/b217d9f2-1fb7-4af3-af2d-3a78d2651e2a.json
Create b217d9f2-1fb7-4af3-af2d-3a78d2651e2a.json
> ✨ Adding snoiva

- app_chains/30e7a72d-b330-4b61-90bb-5087553e5fdc.json
This is my first Avail AppChain named faisal
> ✨ Adding AppChain mclachsss faisal

- app_chains/e9a4b7d3-1283-4873-a85f-0a676641486b.json
This is my first Avail AppChain named johnwick
> ✨ Adding johnwick

- app_chains/0477f6f8-31b0-4842-b4a7-56be530ed531.json
This is my first Avail AppChain named edgeman
> ✨ Adding AppChain edgeman

- app_chains/c81e5402-18f0-4216-a8ed-69adddaf5f34.json
This is my first Avail AppChain named infinitymadara
> ✨ Adding infinitymadara

- app_chains/a367f313-12c8-4bc1-92ca-a4fca0574ba0.json
This is my first Avail AppChain named jewel
> ✨ Adding AppChain jewel

- app_chains/daea1db1-103a-469f-b82b-b01b69f7b456.json
> ✨ Adding AppChain

- app_chains/148293f3-6945-431a-840c-e176e8ba162b.json
> ✨Adding madchain

- 4e39f213-27f6-4a87-8830-f545a0db6503.json
- app_chains/4e39f213-27f6-4a87-8830-f545a0db6503.json
This is my first Avail AppChain named cupon
> ✨ Adding AppChain cupon

- app_chains/75f90eff-876f-4171-bfde-9ddadd806c07.json
> ✨ Adding RFA

- app_chains/57ea4639-6a86-4497-ae52-b1d7c1cad939.json
Adding a new AppChain named katakijoduduk by adding all the relevant details in a JSON file inside the app-chains folder.
> Add katakijoduduk

- app_chains/13f190a2-7aa1-43c8-bb79-96199af690be.json
> Add files via upload✨Adding nmehd

- app_chains/fdf6a766-a45f-4889-86b7-184905bead47.json
✨ Adding hongnhung my appchain
> ✨ Adding hongnhung

- app_chains/157f4323-4859-481e-8e40-77e986c6d105.json
This is my first Avail AppChain named richseokL
> Adding AppChain richseokL
